# StageTwo System Settings
# Generated automatically - edit as needed

CIRCUITPY_WIFI_SSID = "Access 316"
CIRCUITPY_WIFI_PASSWORD = "ZaiyEden2024!"
DEFAULT_BOOT_FILE = "code.py"
BOOT_TIMEOUT = "3"
DEVELOPER_MODE = False
FLASH_WRITE = False
DISPLAY_BRIGHTNESS = 0.5
SD_CARD_ENABLED = True
WIFI_ENABLED = True
NTP_ENABLED = True
SCREENSAVER_ENABLED = True
SCREENSAVER_TIMEOUT = 60
SCREENSAVER_TYPE = trippy
